### ISSUE TITLE
Eager loading for liked items

### ISSUE THREAD

**Issue by TUNER88** [rtconner/laravel-likeable#9]
I want to display a table with likeable items, each row should have like/unlike button.
To get current state of like/unlike for each row, I have make new SQL request for each row. 
`$article->liked();`

How can reduce the number of queries?

My query for the grid:

``` php
$query = (new File())->with('user')->with('organisation')->with('likes')->newQuery();
```

Many thanks in advance.

![screen shot 2015-07-17 at 11 52 15](https://cloud.githubusercontent.com/assets/1565397/8744809/722ca402-2c7a-11e5-9981-88332ce7d5b2.png)

**Comment by guyyosan** [comment]
you can just do this in your with...

```
with('user', 'organisation', 'likes')
```

**Comment by Akeri** [comment]
I'm having the same issue and my query is:

```
$posts = Post::with('categories', 'tagged', 'likeCounter', 'likes')
            ->where('publish_date', '<=', date('Y-m-d H:i:s'))
            ->orderBy('publish_date', 'desc')->get();
```

Getting one query foreach $post->liked($user_id)

What am I doing wrong? Thanks in advance

**Comment by federico77** [comment]
Hello, I have the sam kind of issue and the @guyyosan trick of using ->with('likes') is not working.
I believe the issue lies within the "liked()" method in the trait as it states:

```
return (bool) $this->likes()
    ->where('user_id', '=', $userId)
    ->count();
```
I'm not an expert of eager loading just yet but I guess this method hits the DB no matter what.
Does anyone know of a workaround or an existing fix to this behaviour?

Thanks in advance.

**Comment by mydnic** [comment]
No solution for this ?
